env: dev

replicaCount: 1

ingress:
  http:
    host: api.dev.goshop.quangdang.dev
  grpc:
    host: grpc.dev.goshop.quangdang.dev

autoscaling:
  enabled: false

externalSecret:
  dopplerEnvironment: dev

podDisruptionBudget:
  enabled: false
