apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
    creationPolicy: Owner
  data:
    - {secretKey: AUTHENTIK_SECRET_KEY,         remoteRef: {key: AUTHENTIK_SECRET_KEY}}
    - {secretKey: AUTHENTIK_POSTGRES_PASSWORD,  remoteRef: {key: AUTHENTIK_POSTGRES_PASSWORD}}
    - {secretKey: AUTHENTIK_BOOTSTRAP_PASSWORD, remoteRef: {key: AUTHENTIK_BOOTSTRAP_PASSWORD}}
    - {secretKey: AUTHENTIK_BOOTSTRAP_TOKEN,    remoteRef: {key: AUTHENTIK_BOOTSTRAP_TOKEN}}
