apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: goshop-api
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: goshop
      app.kubernetes.io/instance: goshop
      app.kubernetes.io/component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: goshop-web
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: goshop
      app.kubernetes.io/instance: goshop
      app.kubernetes.io/component: web
