apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: goshop-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: goshop-secrets
    creationPolicy: Owner
  data:
    - {secretKey: auth_secret,            remoteRef: {key: AUTH_SECRET}}
    - {secretKey: database_uri,           remoteRef: {key: DATABASE_URI}}
    - {secretKey: redis_uri,              remoteRef: {key: REDIS_URI}}
    - {secretKey: redis_password,         remoteRef: {key: REDIS_PASSWORD}}
    - {secretKey: stripe_secret_key,      remoteRef: {key: STRIPE_SECRET_KEY}}
    - {secretKey: stripe_webhook_secret,  remoteRef: {key: STRIPE_WEBHOOK_SECRET}}
    - {secretKey: stripe_publishable_key, remoteRef: {key: STRIPE_PUBLISHABLE_KEY}}
    - {secretKey: smtp_user,              remoteRef: {key: SMTP_USER}}
    - {secretKey: smtp_password,          remoteRef: {key: SMTP_PASSWORD}}
