apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snapnews
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/quangdangfit/deployment
      targetRevision: main
      path: charts/webapp
      helm:
        releaseName: snapnews
        valueFiles:
          - $values/apps/snapnews/values.yaml
    - repoURL: https://github.com/quangdangfit/deployment
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: snapnews
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
