apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: goshop-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: goshop-secrets
    creationPolicy: Owner
  data:
    - secretKey: AUTH_SECRET
      remoteRef: { key: AUTH_SECRET }
    - secretKey: STRIPE_SECRET_KEY
      remoteRef: { key: STRIPE_SECRET_KEY }
    - secretKey: STRIPE_WEBHOOK_SECRET
      remoteRef: { key: STRIPE_WEBHOOK_SECRET }
    - secretKey: STRIPE_PUBLISHABLE_KEY
      remoteRef: { key: STRIPE_PUBLISHABLE_KEY }
    - secretKey: SMTP_USER
      remoteRef: { key: SMTP_USER }
    - secretKey: SMTP_PASSWORD
      remoteRef: { key: SMTP_PASSWORD }
