apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: goshop
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.38
    helm:
      releaseName: postgresql
      values: |
        auth:
          existingSecret: postgres-credentials
          secretKeys:
            adminPasswordKey: postgres-password
            userPasswordKey: password
            replicationPasswordKey: replication-password
          username: goshop
          database: goshop
        primary:
          persistence:
            storageClass: local-path
            size: 20Gi
          resources:
            requests: { cpu: 250m, memory: 512Mi }
            limits:   { cpu: 1000m, memory: 1Gi }
          pgHbaConfiguration: |
            local all all trust
            host all all 10.42.0.0/16 md5
            host all all 127.0.0.1/32 md5
            host all all ::1/128 md5
        metrics:
          enabled: false
        volumePermissions:
          enabled: true
        backup:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: data
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: postgres-credentials
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef: { key: POSTGRES_ADMIN_PASSWORD }
    - secretKey: password
      remoteRef: { key: POSTGRES_PASSWORD }
    - secretKey: replication-password
      remoteRef: { key: POSTGRES_REPLICATION_PASSWORD }
