apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "goshop.fullname" . }}-config
  labels: {{- include "goshop.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ toYaml .Values.config | indent 4 }}
