{{- if .Values.ingress.http.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "goshop.fullname" . }}-http
  labels: {{- include "goshop.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts: [{{ .Values.ingress.http.host | quote }}]
      secretName: {{ include "goshop.fullname" . }}-http-tls
  rules:
    - host: {{ .Values.ingress.http.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "goshop.fullname" . }}
                port:
                  name: http
{{- end }}
