{{- if .Values.migration.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "goshop.fullname" . }}-migrate
  labels: {{- include "goshop.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels: {{- include "goshop.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      securityContext: {{- toYaml .Values.securityContext.pod | nindent 8 }}
      containers:
        - name: migrate
          image: {{ include "goshop.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext: {{- toYaml .Values.securityContext.container | nindent 12 }}
          command: {{- toYaml .Values.migration.command | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ include "goshop.fullname" . }}-secrets
          resources:
            requests: { cpu: 100m, memory: 128Mi }
            limits:   { cpu: 500m, memory: 256Mi }
          volumeMounts:
            - name: config
              mountPath: /etc/goshop
              readOnly: true
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: config
          configMap:
            name: {{ include "goshop.fullname" . }}-config
        - name: tmp
          emptyDir: {}
{{- end }}
