apiVersion: v1
kind: Service
metadata:
  name: {{ include "goshop.fullname" . }}
  labels: {{- include "goshop.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.ports.grpc }}
      targetPort: grpc
      protocol: TCP
  selector: {{- include "goshop.selectorLabels" . | nindent 4 }}
